FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# Not necessary as you are referencing the files on local folder.
# However, we are leaving it here because in future we might not use docker volumes or docker compose.
COPY . .

CMD ["npm", "run", "start"]